name : Begineer CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name : Say hello
        run: echo "Workflow is running!"
      - name : Prints current working directory
        run: pwd

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
       
      - name : checking node version
        run : node --version
      


      